{{- if eq true .Values.cloudOne.vulnerabilityScanning.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: workload-operator-role
  labels:
    {{- include "workloadOperator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - batch
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  - ""
  - apps
  resources:
  - cronjobs
  - jobs
  - pods
  - replicationcontrollers
  - replicasets
  - daemonsets
  - statefulsets
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudone.trendmicro.com
  resources:
  - workloadimages
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workload-operator-rolebinding
  labels:
    {{- include "workloadOperator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workload-operator-role
subjects:
- kind: ServiceAccount
  name: {{ include "workloadOperator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
